### PR TITLE
Spectrometers 2019

### PR DESCRIPTION
**Pull request by jmakous**
Updated for 2019

### CODE REVIEW

**Comment by glangsto** [comment]
Hi

Thanks for your upgrades to gr-radio_astro.

I’ve been adding some changes to improve NsfIntegrate and NsfDetect

These are working pretty well and I’ve had the running continuously on 
Raspberry Pi3B+ and Pi4.   Also have the code running on an Odroid N2

I look forward to trying your new programs.

Glen

Note that I’ve changed the shared code a little bit to avoid requiring
installing h5py unless it is absolutely necessary.

(Ie try:
	import h5py
except:
	print warning message.
)

For some systems I’ve had trouble getting pip install of h5py to work.

Glen

**Comment by PranavSanghavi** [comment]
> Hi Thanks for your upgrades to gr-radio_astro. I’ve been adding some changes to improve NsfIntegrate and NsfDetect These are working pretty well and I’ve had the running continuously on Raspberry Pi3B+ and Pi4. Also have the code running on an Odroid N2 I look forward to trying your new programs. Glen Note that I’ve changed the shared code a little bit to avoid requiring installing h5py unless it is absolutely necessary. (Ie try: import h5py except: print warning message. ) For some systems I’ve had trouble getting pip install of h5py to work. Glen
> […](#)

We've been avoiding pip to install h5py and using the apt install to install h5py instead. on the to do is to figure out a windows build.

**Comment by glangsto** [comment]
Thanks

sudo apt-get install python-h5py 

does work fine.

Glen

PS I still recommend putting all python 

imports

inside of

try:
	import h5py
except:
	print “How to fix this problem:”

Type code in your python.

Thanks again,

Glen

**Comment by PranavSanghavi** [comment]
> Thanks sudo apt-get install python-h5py does work fine. Glen PS I still recommend putting all python imports inside of try: import h5py except: print “How to fix this problem:” Type code in your python. Thanks again, Glen
> […](#)

Thanks, I'm making the necessary changes. Should be committing them asap. 

Best, Pranav

**Comment by glangsto** [comment]
Hi Pranav and all,

I had trouble signing into the discussion today.  I’ll have to
give this a test with someone before the next meeting.

It might be that I have multiple accounts and the one I’m trying
is not the one that I was invited with.

Hope the meeting went well.

Best regards

Glen



> On Jul 23, 2019, at 9:31 PM, Pranav Sanghavi <notifications@github.com> wrote:
> 
> Hi Thanks for your upgrades to gr-radio_astro. I’ve been adding some changes to improve NsfIntegrate and NsfDetect These are working pretty well and I’ve had the running continuously on Raspberry Pi3B+ and Pi4. Also have the code running on an Odroid N2 I look forward to trying your new programs. Glen Note that I’ve changed the shared code a little bit to avoid requiring installing h5py unless it is absolutely necessary. (Ie try: import h5py except: print warning message. ) For some systems I’ve had trouble getting pip install of h5py to work. Glen
> …
> 
> We've been avoiding pip to install h5py and using the apt install to install h5py instead. on the to do is to figure out a windows build.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/WVURAIL/gr-radio_astro/pull/18?email_source=notifications\u0026email_token=AADRXGGKJWMTSOUADXMBNELQA6WH7A5CNFSM4IGDV7A2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2U4PHQ#issuecomment-514443166", "url": "https://github.com/WVURAIL/gr-radio_astro/pull/18?email_source=notifications\u0026email_token=AADRXGGKJWMTSOUADXMBNELQA6WH7A5CNFSM4IGDV7A2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2U4PHQ#issuecomment-514443166", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]



Glen I Langston, Ph. D.
Galactic Astronomy Program Director
National Science Foundation
2415 Eisenhower Avenue
Alexandria, VA 22314
P: 703-292-4937
C: 703-470-9820
glangsto@nsf.gov

**Comment by PranavSanghavi** [comment]
> Hi Pranav and all, I had trouble signing into the discussion today. I’ll have to give this a test with someone before the next meeting. It might be that I have multiple accounts and the one I’m trying is not the one that I was invited with. Hope the meeting went well. Best regards Glen
> On Jul 23, 2019, at 9:31 PM, Pranav Sanghavi ***@***.***> wrote: Hi Thanks for your upgrades to gr-radio_astro. I’ve been adding some changes to improve NsfIntegrate and NsfDetect These are working pretty well and I’ve had the running continuously on Raspberry Pi3B+ and Pi4. Also have the code running on an Odroid N2 I look forward to trying your new programs. Glen Note that I’ve changed the shared code a little bit to avoid requiring installing h5py unless it is absolutely necessary. (Ie try: import h5py except: print warning message. ) For some systems I’ve had trouble getting pip install of h5py to work. Glen … We've been avoiding pip to install h5py and using the apt install to install h5py instead. on the to do is to figure out a windows build. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "#18?email_source=notifications\u0026email_token=AADRXGGKJWMTSOUADXMBNELQA6WH7A5CNFSM4IGDV7A2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2U4PHQ#issuecomment-514443166", "url": "#18?email_source=notifications\u0026email_token=AADRXGGKJWMTSOUADXMBNELQA6WH7A5CNFSM4IGDV7A2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2U4PHQ#issuecomment-514443166", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
> Glen I Langston, Ph. D. Galactic Astronomy Program Director National Science Foundation 2415 Eisenhower Avenue Alexandria, VA 22314 P: 703-292-4937 C: 703-470-9820 glangsto@nsf.gov

Hi, i am so sorry fro there late response. have been quite ill this past week. The meeting went well. Seem so to meet our aim to have everybody involved post the summer as long as we keep on going.  I just sent out the minutes of the meeting. I believe I've attached both of your email addresses the mail app suggested.

**Pull request merged**
